### ISSUE TITLE
More info about this project

### ISSUE THREAD

**Issue by brunobertechini** [yinchang0626/abp.ng#19]
First of all, well done on this project m8 👍 

I would like to understand what is the purpose of this project for developers.

- Is it a template or starter kit ?
- Is it to demonstrate how to integrate different UI themes?

My question: I want to use ngx-admin with Abp and Im trying to understand this source code to be able to do that...but i dont think I need the packages / abp source code for that...IS there a reason why not install the npm packages instead of cloning the sources?

Can you shed some light ?

Thanks

**Comment by yinchang0626** [comment]
1.Yes,It's Template for developing Library.

2.Yes,we also shows how to extend existed library without modify abp's code,and learning abp's angular-project

3.
With the source code of themes and abp,it is easier to figure out which part of the package is failing after version changed.
For example,the packages of abp (include angular) and ng-alain  will upgrade its version over time.
It is convenient to have source code after upgrade angular,
if there's breaking changes,we can easily figure out which part of the source code fails,and it's eaiser to follow abp's design and coding style
