### ISSUE TITLE
Can't build abp.theme-shared

### ISSUE THREAD

**Issue by lktiep** [yinchang0626/abp.ng#4]
I've pulled your code and try to build, til this step:

`ng build abp.theme-shared`

Then it raises errors like this: 

```
------------------------------------------------------------------------------
Building entry point '@abp/ng.theme.shared'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: error TS6059: File 'C:/Users/xxx/source/repos/yinchang0626/abp.ng/packages/core/src/lib/abstracts/index.ts' is not under 'rootDir' 'C:\Users\xxx\source\repos\yinchang0626\abp.ng\packages\theme-shared\src'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/xxx/source/repos/yinchang0626/abp.ng/packages/core/src/lib/abstracts/ng-model.component.ts' is not under 'rootDir' 'C:\Users\xxx\source\repos\yinchang0626\abp.ng\packages\theme-shared\src'. 'rootDir' is expected to contain all source files.

```

Do you have any idea?

**Comment by yinchang0626** [comment]
before build abp.theme-shared ,
you need to modify tsconfig in root directory 
from "@abp/ng.core": [ "packages/core/src/public-api.ts" ], to "@abp/ng.core": [ "dist/core" ],

by the way, i pushed that in repository,so you can serve app without build but if you modify code in packages/theme-shared or packages/core ,then you need rebuild that

**Comment by lktiep** [comment]
> 
> 
> before build abp.theme-shared ,
> you need to modify tsconfig in root directory
> from "@abp/ng.core": [ "packages/core/src/public-api.ts" ], to "@abp/ng.core": [ "dist/core" ],
> 
> by the way, i pushed that in repository,so you can serve app without build but if you modify code in packages/theme-shared or packages/core ,then you need rebuild that

Thanks for your response. Now when I serve ngx-admin-app there is one more error:

`ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'web-animations-js' in 'C:\Users\xxx\source\repos\yinchang0626\abp.ng\apps\ngx-admin-app\src'`

Do you have any idea?

**Comment by yinchang0626** [comment]
Maybe delete package-lock.json file and node_modules directory and retry "npm i" can resolve this problem

**Comment by lktiep** [comment]
One more other error :P
`ERROR in ./src/app/pages/editors/ckeditor/ckeditor.component.ts
Module not found: Error: Can't resolve 'ckeditor' in 'C:\Users\xxx\source\repos\yinchang0626\abp.ng\apps\ngx-admin-app\src\app\pages\editors\ckeditor'`

Before that, it says that the package name was changed:

`ckeditor@4.12.1: We have renamed the @ckeditor package. New versions are available under the @ckeditor4 name.`

**Comment by yinchang0626** [comment]
i fixed it and ,please try again.

**Comment by lktiep** [comment]
> 
> 
> i fixed it and ,please try again.

That works now!!! I'm starting learning it, thanks for your effort!
