### ISSUE TITLE
npm i giving errors

### ISSUE THREAD

**Issue by MROALI** [yinchang0626/abp.ng#5]
Hi,
I am so interrested about your app. But i am having a problem installing dependencies (npm i).

npm WARN deprecated @types/jest-diff@24.3.0: This is a stub types definition. jest-diff provides its own type definitions, so you do not need this installed.
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commons.
npm WARN deprecated rollup-plugin-json@4.0.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fs%2fdev - Not found
npm ERR! 404
npm ERR! 404  '@fs/dev@^1.1.2-alpha.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@fs/ng-alain'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Do you have any idea what to do ?

**Comment by yinchang0626** [comment]
I will fix it , please wait a moment,
by the way ,this is because of I am trying to publish package to npm server ,
If you can create one(ex [verdaccio](https://verdaccio.org/)),and put the all [dist ](https://github.com/yinchang0626/abp.ng/tree/master/dist)packages ,
then npm install from that will avoid error

**Comment by MROALI** [comment]
ok thank you, i will wait until you fix it :)

**Comment by yinchang0626** [comment]
@MROALI 
please try again,
if you have any questions please let me know,thanks
